/**
 * Setup.gs — one-time setup, run by hand from the Apps Script editor.
 * None of these are reachable over HTTP.
 */

/**
 * STEP 1. Generates SHARED_SECRET, then tells you what is still missing.
 *
 * You do NOT edit this file to add credentials. Type them into
 * Project Settings (the gear in the left sidebar) -> Script Properties -> Add.
 *
 * That is deliberate: a credential pasted into a source file gets pushed to
 * Apps Script, committed to git, and then has to be scrubbed out of history.
 * The Script Properties UI never touches your working tree.
 *
 * Safe to re-run. An existing SHARED_SECRET is left alone — regenerating it
 * would break the Slack URLs without warning.
 */
function setupProperties() {
  var store = PropertiesService.getScriptProperties();

  if (!store.getProperty(PROP.SHARED_SECRET)) {
    store.setProperty(PROP.SHARED_SECRET, generateSecret_());
    Logger.log('Generated a new SHARED_SECRET.');
  } else {
    Logger.log('SHARED_SECRET already set — left as is.');
  }

  Logger.log('\nSHARED_SECRET:\n' + store.getProperty(PROP.SHARED_SECRET) +
             '\n\nAppend  ?s=<that>  to the web app URL, in Slack and in the ' +
             'browser health check.');

  var missing = missingProperties_();
  if (!missing.length) {
    Logger.log('\nAll properties are set. Next: setupSheet, setupTrigger, verifySetup.');
    return;
  }

  Logger.log('\nStill to add, in Project Settings -> Script Properties:');
  missing.forEach(function (name) {
    Logger.log('  ' + name + '  —  ' + (PROP_HELP[name] || ''));
  });
}

/** Required property names with no value yet. Optional ones are ignored. */
function missingProperties_() {
  var store = PropertiesService.getScriptProperties();
  return Object.keys(PROP).filter(function (name) {
    return OPTIONAL_PROPS.indexOf(name) === -1 && !store.getProperty(PROP[name]);
  });
}

/**
 * Print the Freshdesk groups and their IDs.
 *
 * Run this when a ticket fails with "group_id: It should be a/an Positive
 * Integer" — that means Group is mandatory on your account, and the fix is to
 * put one of these IDs into the FRESHDESK_GROUP_ID script property.
 */
function listGroups() {
  var res = UrlFetchApp.fetch(fdBaseUrl_() + '/groups', {
    method: 'get',
    headers: { Authorization: fdAuthHeader_() },
    muteHttpExceptions: true
  });

  if (res.getResponseCode() !== 200) {
    Logger.log('Could not list groups: ' +
               describeFdError_(res.getResponseCode(), res.getContentText()));

    if (res.getResponseCode() === 403) {
      // Listing groups is an admin action; creating tickets is not. A plain
      // agent key fails here and works perfectly well for everything else,
      // so this is not a reason to go asking for a wider key.
      Logger.log(
        '\nThat is expected for a non-admin agent API key — listing groups needs ' +
        'admin rights, creating tickets does not.\n' +
        'Get the ID from the Freshdesk UI instead: Admin -> Groups -> open the ' +
        'group, and take the number from the URL.\n' +
        'Then put it in the FRESHDESK_GROUP_ID script property.');
    }
    return;
  }

  var groups = JSON.parse(res.getContentText() || '[]');
  if (!groups.length) {
    Logger.log('No groups on this account. Ask the Freshdesk admin to create one, ' +
               'or make the Group field optional under Admin -> Ticket Fields.');
    return;
  }

  Logger.log('Freshdesk groups — put one of these IDs in FRESHDESK_GROUP_ID:');
  groups.forEach(function (g) {
    Logger.log('  ' + g.id + '  ' + g.name + (g.description ? '  — ' + g.description : ''));
  });
}

function generateSecret_() {
  var bytes = [];
  for (var i = 0; i < 32; i++) bytes.push(Math.floor(Math.random() * 256));
  return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/, '');
}

/** Print the current secret — e.g. when you need the health check URL again. */
function showSharedSecret() {
  Logger.log(cfg_(PROP.SHARED_SECRET));
}

/** Rotate it. Update BOTH Slack request URLs immediately afterwards. */
function rotateSharedSecret() {
  var s = generateSecret_();
  PropertiesService.getScriptProperties().setProperty(PROP.SHARED_SECRET, s);
  Logger.log('New secret: ' + s + '\nUpdate both URLs in the Slack app config NOW — ' +
             'until you do, every submission is rejected.');
}

/** STEP 2. Create the log tab and its header row. Safe to re-run. */
function setupSheet() {
  var sh = sheet_();
  Logger.log('Sheet ready: "' + sh.getName() + '" with ' +
             Math.max(0, sh.getLastRow() - 1) + ' logged submission(s).');
}

/**
 * STEP 3. Install the every-minute worker. Safe to re-run.
 *
 * This is the safety net, not the fast path — a submission also fires a
 * one-off trigger of its own, so tickets are normally created within seconds.
 * Without this one, a submission whose one-off failed to fire would sit in
 * the Sheet as 'pending' forever.
 */
function setupTrigger() {
  var stale = ['processQueue', 'processQueueOnce', 'processAttachments'];
  var existing = ScriptApp.getProjectTriggers();
  for (var i = 0; i < existing.length; i++) {
    if (stale.indexOf(existing[i].getHandlerFunction()) > -1) {
      ScriptApp.deleteTrigger(existing[i]);
    }
  }
  ScriptApp.newTrigger('processQueue').timeBased().everyMinutes(1).create();
  Logger.log('Trigger installed: processQueue, every minute.');
}

/**
 * STEP 4. Confirm everything answers, without creating anything.
 * Must print "All checks passed" before you go near a real ticket.
 */
function verifySetup() {
  var problems = [];

  // Catches the PROP-edited-by-hand mistake before anything else confuses us.
  Object.keys(PROP).forEach(function (name) {
    if (PROP[name] !== name) {
      problems.push('Config.gs: PROP.' + name + ' should be the string "' + name +
                    '", but is "' + String(PROP[name]).slice(0, 40) + '". ' +
                    'PROP maps property NAMES; real values go in Script Properties.');
    }
  });

  missingProperties_().forEach(function (name) {
    problems.push('Missing property: ' + name + ' — ' + (PROP_HELP[name] || ''));
  });

  // Slack
  try {
    var auth = slackApi_('auth.test', {});
    if (!auth.ok) problems.push('Slack auth.test failed: ' + auth.error);
    else Logger.log('Slack OK — bot "' + auth.user + '" in team "' + auth.team + '"');
  } catch (e) {
    problems.push('Slack unreachable: ' + e);
  }

  // Freshdesk — a GET, so nothing is created
  try {
    var res = UrlFetchApp.fetch(fdBaseUrl_() + '/tickets?per_page=1', {
      method: 'get',
      headers: { Authorization: fdAuthHeader_() },
      muteHttpExceptions: true
    });
    if (res.getResponseCode() === 200) Logger.log('Freshdesk OK');
    else problems.push('Freshdesk: ' + describeFdError_(res.getResponseCode(), res.getContentText()));
  } catch (e) {
    problems.push('Freshdesk unreachable: ' + e);
  }

  // Sheet
  try {
    Logger.log('Sheet OK — ' + Math.max(0, sheet_().getLastRow() - 1) + ' row(s)');
  } catch (e) {
    problems.push('Sheet unreachable: ' + e);
  }

  // Trigger
  var hasTrigger = ScriptApp.getProjectTriggers().some(function (t) {
    return t.getHandlerFunction() === 'processQueue';
  });
  if (!hasTrigger) problems.push('No processQueue trigger — run setupTrigger(). ' +
                                 'Without it, nothing that the modal queues is ever processed.');

  Logger.log(problems.length ? 'PROBLEMS:\n- ' + problems.join('\n- ')
                             : '\nAll checks passed.');
}

/**
 * Post the "Create a ticket" button into a channel. Run once per channel.
 * The slash command works without this; the button is for discoverability.
 */
function postLauncher(channelId) {
  // The editor's Run button cannot pass an argument, and running this from
  // the editor is the only way anyone will ever call it. So the channel can
  // come from a script property instead.
  channelId = channelId || cfg_(PROP.LAUNCHER_CHANNEL_ID, '');

  if (!channelId) {
    Logger.log(
      'No channel to post to.\n\n' +
      'Add a script property LAUNCHER_CHANNEL_ID with the channel ID, then run ' +
      'this again:\n' +
      '  Project Settings (gear, left sidebar) -> Script Properties -> Add\n\n' +
      'The channel ID is at the bottom of the channel\'s About tab, and looks ' +
      'like C0123ABCD.\n\n' +
      'Posting to several channels? Change the property and run this again for ' +
      'each one.');
    return;
  }

  var res = postMessage_(channelId, 'Need help? Create a support ticket.',
                         buildLauncherBlocks_());

  if (!res.ok) {
    Logger.log('Failed: ' + res.error +
               (res.error === 'not_in_channel' || res.error === 'channel_not_found'
                 ? '\n\nInvite the bot first: /invite @Support Tickets in that channel. ' +
                   'The app does not request chat:write.public, so it can only post ' +
                   'where it has been invited.'
                 : ''));
    return;
  }

  Logger.log('Launcher posted to ' + channelId + '.\n\n' +
             'Pin it — the button keeps working for as long as the message exists, ' +
             'but an unpinned one scrolls away and people forget the ticket form ' +
             'is there at all.');
}

/**
 * Find out how large a single create-with-attachments request this project can
 * actually assemble, without touching Slack or Freshdesk.
 *
 * MAX_INLINE_ATTACH_BYTES starts conservative because Apps Script does not
 * document its memory ceiling. This builds a body of the given size from
 * dummy bytes and reports whether it survived and how long it took, so the
 * setting comes from measurement rather than from my guess.
 *
 * Run it upwards — 5, 10, 15, 20, 25 — until it fails, then set
 * MAX_INLINE_ATTACH_BYTES a little below the last size that worked.
 */
function probeInlineLimit(megabytes) {
  var mb = Number(megabytes) || 5;
  var started = Date.now();

  try {
    // A distinct array per file. Sharing one would make the probe optimistic
    // about exactly the thing it is measuring.
    var files = [];
    for (var f = 0; f < mb; f++) {
      var chunk = new Array(1024 * 1024);
      for (var i = 0; i < chunk.length; i++) chunk[i] = 65;
      files.push({ field: 'attachments[]', filename: 'probe' + f + '.bin',
                   mimeType: 'application/octet-stream', bytes: chunk });
    }

    var body = buildMultipart_([{ name: 'subject', value: 'probe' }], files);
    var cap = Math.round(MAX_ATTACH_TOTAL_BYTES / (1024 * 1024));
    Logger.log('OK at ' + mb + 'MB — assembled ' + body.payload.length +
               ' bytes in ' + (Date.now() - started) + 'ms.' +
               (mb >= cap
                 ? '\n\nThat is the whole upload cap, so every submission can be ' +
                   'created with its files attached. Nothing further to change.'
                 : '\n\nTry the next size up. MAX_INLINE_ATTACH_BYTES should be at ' +
                   'least MAX_ATTACH_TOTAL_BYTES (' + cap + 'MB) for every ticket ' +
                   'to arrive complete.'));
  } catch (e) {
    Logger.log('FAILED at ' + mb + 'MB after ' + (Date.now() - started) + 'ms: ' + e +
               '\nSet MAX_INLINE_ATTACH_BYTES below this. Anything larger takes ' +
               'the create-then-attach route, which streams and has no such limit.');
  }
}

/**
 * Print the state of the integration: triggers, unfinished work, and the last
 * few submissions with their timings.
 *
 * Run this first whenever something looks wrong. "A trigger exists" and "the
 * trigger points at a function that still exists" are different things, and
 * the difference is invisible until you read an execution log.
 */
function diagnose() {
  var out = ['=== Triggers ==='];
  var known = ['processQueue', 'processQueueOnce'];
  var triggers = ScriptApp.getProjectTriggers();

  if (!triggers.length) {
    out.push('  NONE — run setupTrigger(). Nothing queued will ever be processed.');
  }
  triggers.forEach(function (t) {
    var fn = t.getHandlerFunction();
    var bad = known.indexOf(fn) === -1;
    out.push('  ' + fn + (bad
      ? '   <-- STALE. This function no longer exists; the trigger fails every' +
        ' time it fires. Run setupTrigger() to replace it.'
      : ''));
  });
  if (!triggers.some(function (t) { return t.getHandlerFunction() === 'processQueue'; })) {
    out.push('  Missing the every-minute processQueue trigger — run setupTrigger().');
  }

  out.push('', '=== Unfinished work ===');
  try {
    var queued = Object.keys(PropertiesService.getScriptProperties().getProperties())
      .filter(function (k) { return k.indexOf('job:') === 0; }).length;
    out.push('  submitted, not yet logged : ' + queued +
             (queued ? '   <-- the worker has not run since these were submitted' : ''));
  } catch (e) {
    out.push('  could not read the property store: ' + e);
  }
  try {
    out.push('  tickets not yet created : ' + pendingTicketRows_().length);
    out.push('  files not yet uploaded  : ' + pendingAttachmentRows_().length);
  } catch (e) {
    out.push('  could not read the sheet: ' + e);
  }

  out.push('', '=== Last 5 submissions ===');
  try {
    var sh = sheet_();
    var last = sh.getLastRow();
    var from = Math.max(2, last - 4);
    if (last < 2) {
      out.push('  none yet');
    } else {
      sh.getRange(from, 1, last - from + 1, HEADERS.length).getValues().forEach(function (r, i) {
        var channel = rowVal_(r, 'channel_id');
        var ts = rowVal_(r, 'slack_ts');

        out.push('  row ' + (from + i) +
                 ' | ' + rowVal_(r, 'status') +
                 ' | ticket ' + (rowVal_(r, 'freshdesk_ticket_id') || '-') +
                 ' | files ' + rowVal_(r, 'file_count') + ' ' + rowVal_(r, 'attach_status') +
                 ' | ack ' + rowVal_(r, 'ack_ms') + 'ms' +
                 ' | total ' + (rowVal_(r, 'duration_ms') || '-') + 'ms');

        // The summary is the part with no error column of its own, so say
        // plainly whether it went out and where it was supposed to go.
        out.push('        channel ' + (channel || '(none — opened from a shortcut or a DM)') +
                 ' | summary ' + (ts ? 'posted' : 'NOT POSTED'));
        if (channel && !ts) {
          out.push('        the bot is probably not in that channel. ' +
                   '/invite @Support Tickets there — the app has no chat:write.public. ' +
                   'The exact reason is in Executions, logged as ' +
                   '"could not post the channel summary".');
        }

        var err = rowVal_(r, 'error') || rowVal_(r, 'attach_error');
        if (err) out.push('        ' + truncate_(String(err), 200));
      });
      out.push('', '  ack is the Slack 3-second budget. Anything near 2500ms is the problem.');
    }
  } catch (e) {
    out.push('  could not read the sheet: ' + e);
  }

  Logger.log(out.join('\n'));
}

/**
 * Create one real ticket from the editor, printing the exact payload and the
 * raw Freshdesk response.
 *
 * This takes Slack out of the picture completely. When a submission fails,
 * run it: if it fails here too the problem is the ticket payload, and you can
 * see every field that was sent. If it succeeds here but not from Slack, the
 * problem is somewhere between Slack and the web app instead.
 */
function testCreateTicket() {
  var t = {
    userId: 'U_TEST', userName: 'setup-test',
    email: Session.getActiveUser().getEmail() || 'setup-test@example.com',
    channelId: '', channelName: 'setup-test',
    subject: 'Setup test ' + nowIso_(),
    description: 'Created by testCreateTicket(). Safe to close.',
    priority: 'Low', files: []
  };

  Logger.log('Sending this payload to ' + fdBaseUrl_() + '/tickets :\n' +
             JSON.stringify(buildTicketPayload_(t), null, 2));

  var res = createTicket_(t);

  if (res.ok) {
    Logger.log('\nCreated ticket #' + res.ticketId + '\n' + ticketUrl_(res.ticketId));
  } else {
    Logger.log('\nHTTP ' + res.httpStatus + '\n' + res.error +
               '\n\nFRESHDESK_GROUP_ID is currently: "' +
               cfg_(PROP.FRESHDESK_GROUP_ID, '(not set)') + '"' +
               '\nIf that says (not set) but you added it, check the spelling of the ' +
               'property name and that you saved it in THIS script project.');
  }
}

/**
 * Latency check. Creates ONE real ticket in whatever Freshdesk account is
 * configured, so point FRESHDESK_DOMAIN at a sandbox before running it.
 *
 * Slack allows 3 seconds for a modal submission. Run this a dozen times
 * across a working day — Apps Script cold starts vary with idle time — and
 * if the numbers crowd 2500ms, that is the signal to stop creating the
 * ticket inline and defer it the way attachments already are.
 */
function spikeLatency() {
  var started = Date.now();
  var r = createTicket_({
    userId: 'U_TEST', userName: 'latency-spike',
    email: 'latency-spike@example.com',
    channelId: '', channelName: 'spike',
    subject: 'Latency spike ' + nowIso_(),
    description: 'Automated timing test. Safe to close.',
    priority: 'Low', files: []
  });
  Logger.log('Freshdesk round-trip: ' + (Date.now() - started) + 'ms — ' +
             (r.ok ? 'ticket #' + r.ticketId : 'FAILED ' + r.error));
}
